"""Every WAV saved by ``utils.audio.save_audio`` carries an AI-generated disclosure (T051, FR-026).

The disclosure is written into the WAV's RIFF ``LIST/INFO`` chunk through libsndfile
(``ICMT`` comment, ``ISFT`` software). It is read back two ways: through soundfile and by
walking the raw RIFF chunks. The audio itself must not change: the ``data`` chunk is
compared byte for byte with what the pre-T051 code path (``sf.write(..., format="WAV")``)
writes, and the atomic temp-file write and its cleanup behave as before.
"""

from __future__ import annotations

import os
import struct
from pathlib import Path

import numpy as np
import pytest
import soundfile as sf

from backend.utils import audio as audio_mod

DISCLOSURE = "AI-generated by Voicebox"


def _riff_chunks(raw: bytes) -> dict[bytes, bytes]:
    """Top-level chunks of a RIFF/WAVE file, by id (the last one wins)."""
    assert raw[:4] == b"RIFF", raw[:12]
    assert raw[8:12] == b"WAVE", raw[:12]
    chunks: dict[bytes, bytes] = {}
    pos = 12
    while pos + 8 <= len(raw):
        cid = raw[pos : pos + 4]
        (size,) = struct.unpack("<I", raw[pos + 4 : pos + 8])
        chunks[cid] = raw[pos + 8 : pos + 8 + size]
        pos += 8 + size + (size & 1)
    return chunks


def _info_tags(raw: bytes) -> dict[str, str]:
    """Sub-chunks of the LIST/INFO chunk, decoded and stripped of NUL padding."""
    chunks = _riff_chunks(raw)
    listing = chunks.get(b"LIST")
    if listing is None or listing[:4] != b"INFO":
        return {}
    tags: dict[str, str] = {}
    pos = 4
    while pos + 8 <= len(listing):
        tid = listing[pos : pos + 4].decode("ascii")
        (size,) = struct.unpack("<I", listing[pos + 4 : pos + 8])
        tags[tid] = listing[pos + 8 : pos + 8 + size].rstrip(b"\x00").decode("utf-8")
        pos += 8 + size + (size & 1)
    return tags


def _signal(channels: int = 1, n: int = 4801) -> np.ndarray:
    rng = np.random.default_rng(1234)
    data = (0.4 * rng.standard_normal((n, channels))).clip(-1, 1).astype(np.float32)
    return data[:, 0] if channels == 1 else data


def _pre_t051_write(audio: np.ndarray, path: Path, sample_rate: int) -> None:
    """What save_audio wrote before T051."""
    sf.write(str(path), audio, sample_rate, format="WAV")


# --- the disclosure --------------------------------------------------------


def test_disclosure_constant_is_the_fr026_text() -> None:
    assert audio_mod.AI_GENERATED_DISCLOSURE == DISCLOSURE


def test_saved_wav_carries_the_disclosure_read_back_through_soundfile(tmp_path: Path) -> None:
    path = tmp_path / "out.wav"

    audio_mod.save_audio(_signal(), str(path), 24000)

    with sf.SoundFile(str(path)) as f:
        assert f.comment == DISCLOSURE
        assert f.software.startswith("Voicebox")


def test_saved_wav_carries_the_disclosure_in_the_raw_riff_info_chunk(tmp_path: Path) -> None:
    path = tmp_path / "out.wav"

    audio_mod.save_audio(_signal(), str(path), 24000)

    tags = _info_tags(path.read_bytes())
    assert tags.get("ICMT") == DISCLOSURE, tags
    assert tags.get("ISFT", "").startswith("Voicebox"), tags


@pytest.mark.parametrize("sample_rate", [16000, 24000, 44100, 48000])
@pytest.mark.parametrize("channels", [1, 2])
def test_every_rate_and_layout_is_tagged(tmp_path: Path, sample_rate: int, channels: int) -> None:
    path = tmp_path / "out.wav"

    audio_mod.save_audio(_signal(channels), str(path), sample_rate)

    assert _info_tags(path.read_bytes()).get("ICMT") == DISCLOSURE


def test_positional_call_still_works_and_default_rate_is_24000(tmp_path: Path) -> None:
    path = tmp_path / "out.wav"

    audio_mod.save_audio(_signal(), str(path))

    assert sf.info(str(path)).samplerate == 24000
    assert _info_tags(path.read_bytes()).get("ICMT") == DISCLOSURE


# --- the audio is unchanged -------------------------------------------------


@pytest.mark.parametrize("sample_rate", [24000, 48000])
@pytest.mark.parametrize("channels", [1, 2])
@pytest.mark.parametrize("dtype", [np.float32, np.float64])
def test_data_chunk_is_byte_identical_to_the_pre_t051_write(tmp_path: Path, sample_rate, channels, dtype) -> None:
    audio = _signal(channels).astype(dtype)
    tagged = tmp_path / "tagged.wav"
    reference = tmp_path / "reference.wav"

    audio_mod.save_audio(audio, str(tagged), sample_rate)
    _pre_t051_write(audio, reference, sample_rate)

    tagged_chunks = _riff_chunks(tagged.read_bytes())
    reference_chunks = _riff_chunks(reference.read_bytes())
    assert tagged_chunks[b"data"] == reference_chunks[b"data"]
    assert tagged_chunks[b"fmt "] == reference_chunks[b"fmt "]


def test_samples_rate_and_subtype_read_back_unchanged(tmp_path: Path) -> None:
    audio = _signal()
    tagged = tmp_path / "tagged.wav"
    reference = tmp_path / "reference.wav"

    audio_mod.save_audio(audio, str(tagged), 48000)
    _pre_t051_write(audio, reference, 48000)

    got, got_sr = sf.read(str(tagged), dtype="int16")
    want, want_sr = sf.read(str(reference), dtype="int16")
    assert got_sr == want_sr == 48000
    np.testing.assert_array_equal(got, want)
    assert sf.info(str(tagged)).subtype == sf.info(str(reference)).subtype == "PCM_16"
    assert sf.info(str(tagged)).frames == len(audio)


# --- the atomic write is unchanged -----------------------------------------


def test_no_temp_file_is_left_after_a_successful_save(tmp_path: Path) -> None:
    path = tmp_path / "nested" / "dir" / "out.wav"

    audio_mod.save_audio(_signal(), str(path), 24000)

    assert path.exists()
    assert not Path(f"{path}.tmp").exists()
    assert sorted(p.name for p in path.parent.iterdir()) == ["out.wav"]


def test_overwrite_replaces_the_file_atomically(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    path = tmp_path / "out.wav"
    path.write_bytes(b"old")
    replaced: list[tuple[str, str]] = []
    real_replace = os.replace

    def spy_replace(src, dst):
        replaced.append((str(src), str(dst)))
        return real_replace(src, dst)

    monkeypatch.setattr(os, "replace", spy_replace)

    audio_mod.save_audio(_signal(), str(path), 24000)

    assert replaced == [(f"{path}.tmp", str(path))]
    assert _info_tags(path.read_bytes()).get("ICMT") == DISCLOSURE


def test_failed_rename_cleans_up_and_keeps_the_old_file(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    path = tmp_path / "out.wav"
    path.write_bytes(b"old")

    def failing_replace(*_a, **_k):
        raise PermissionError("locked")

    monkeypatch.setattr(os, "replace", failing_replace)

    with pytest.raises(OSError, match="Failed to save audio"):
        audio_mod.save_audio(_signal(), str(path), 24000)

    assert path.read_bytes() == b"old"
    assert not Path(f"{path}.tmp").exists()


def test_failed_encode_cleans_up_and_creates_nothing(tmp_path: Path) -> None:
    path = tmp_path / "out.wav"

    with pytest.raises(OSError, match="Failed to save audio"):
        audio_mod.save_audio(_signal(), str(path), 0)  # an invalid rate makes libsndfile refuse

    assert not path.exists()
    assert not Path(f"{path}.tmp").exists()
